# Descargar la imagen oficial de Postgres desde Docker Hub
FROM postgres:15

# Copiar los scripts DDL y DML a la carpeta de inicialización
COPY DDL_Calendario.sql /docker-entrypoint-initdb.d/
COPY DML_Calendario.sql /docker-entrypoint-initdb.d/
